---
title: "Factors"
format: html
---

```{r}
# Get rid of some duplicate rows!
library(tidyverse)

grades <- read.csv("https://mac-stat.github.io/data/grades.csv") |> 
  distinct(sid, sessionID, .keep_all = TRUE)

# Check it out
head(grades)
```
```{r}
grade_distribution <- grades |> 
  count(grade)

head(grade_distribution)
```


## Exercise 1: Changing Order

```{r}
grade_distribution |> 
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```
**Manual reorder**
```{r}
grade_distribution |>
  mutate(grade = fct_relevel(grade, c("A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "NC", "S", "AU"))) |>
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```
**ascending frequency**
```{r}
grade_distribution |>
  mutate(grade = fct_reorder(grade, n)) |>
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```
**descending frequency**
```{r}
grade_distribution |>
  mutate(grade = fct_reorder(grade, n, .desc = TRUE)) |>
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```
## Exercise 2: Changing Factor Level Labels

```{r}
grade_distribution |>
  mutate(grade = fct_relevel(grade, c("A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "NC", "S", "AU"))) |>
  mutate(grade = fct_recode(grade, 
                            "Satisfactory" = "S",
                            "Audit" = "AU")) |>  
  ggplot(aes(x = grade, y = n)) +
    geom_col()
```





























